### ISSUE TITLE
Update Jena?

### ISSUE THREAD

**Issue by osma** [rdfhdt/hdt-java#44]
hdt-java currently uses Jena 3.0.1, which was released in December 2015. Jena 3.2.0 was just released so hdt-java is now three Jena releases behind. There has been a lot of work on Jena, including many fixes to the SPARQL query engine.

I think hdt-java should be upgraded to the newest Jena release. Jena APIs are pretty stable so I don't expect this to be difficult, though I haven't tried (yet).

**Comment by mielvds** [comment]
I agree, should be minor, but will be a 2.0.1 release. Do you want to have a go at it? I'll have a look at your other PRs soon. Thanks for the help!

**Comment by osma** [comment]
Sure, I can try. But as there are very few unit tests, I'm not sure how to verify that everything works after the upgrade...

**Comment by osma** [comment]
Actually, looking at the pom files, the current configuration seems to be a mixture of Jena 3.0.0 and 3.0.1, which is a bit strange.

**Comment by osma** [comment]
This was done in #45

**Comment by osma** [comment]
Actually not, the changes mentioned in #45 were pulled in to the [shawnsmith](https://github.com/rdfhdt/hdt-java/tree/shawnsmith) branch but not applied to `master`.

**Comment by sharpaper** [comment]
[Update Fuseki/Jena dependency to v3.4.0](http://markmail.org/message/xetmwk5akt26oxxj).

**Comment by wonkydonky** [comment]
Any progress on this? Even though HDT is very useful, at the moment it's not usable with Jena/Fuseki because hdt-java still depends on an old version of Jena. I just hit [this error](https://mail-archives.apache.org/mod_mbox/jena-users/201711.mbox/%3CCA%2BwZyetOdfByw15s4h%2BN9qevVL0nBA9yEKk%2Bz_H%2BY6g6cq4R%2BA%40mail.gmail.com%3E) myself, and there is no workaround other than updating the Jena dependency.

**Comment by MarioAriasGa** [comment]
I have upgraded the master branch to the latest Jena version 3.7.0
