### ISSUE TITLE
Slow query

### ISSUE THREAD

**Issue by v4ss4llo** [rdfhdt/hdt-java#65]
Cross posting here since it's probably more relevant: https://github.com/rdfhdt/hdt-cpp/issues/142

**Comment by wonkydonky** [comment]
This *seems* to happen with `ja:namedGraph` but not with `ja:defaultGraph`.

**Comment by afs** [comment]
Further information from the OP: when the correct query is used, using GRAPH to access the named graph, there is no issue.

**Comment by wonkydonky** [comment]
This issue can be closed. It turned out to be a problem/feature of Fuseki. Specifically, a "FROM" clause it triggering the "dynamic datasets" feature which does a lot of duplicates filtering, hence the slowness. This however doesn't seem to happen when using GRAPH.

Sorry for reporting, but it wasn't clear what was causing the very low performance.
